"""add subscription intent

Revision ID: 0971a1d75cab
Revises: 20251226_add_kcb_to_landlord_settings
Create Date: 2026-01-11 17:11:36.298906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0971a1d75cab'
down_revision = '20251226_add_kcb_to_landlord_settings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('last_run', sa.Date(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    op.create_table('subscription_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('backup_subscription')
    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.alter_column('kcb_paybill',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.drop_column('transaction_number')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payment_transaction_id'))
        batch_op.drop_column('verified')

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_properties',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('property_plan_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('property_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.drop_column('address')
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subscription_plan_fk'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'plan', ['plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_property_id'))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscription_plan_fk'), 'plan', ['plan_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('property_owner_id_fkey'), 'user', ['owner_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('property_plan_id_fkey'), 'plan', ['plan_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('duration_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_properties',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_payment_transaction_id'), ['transaction_id'], unique=True)

    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('kcb_paybill',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('backup_subscription',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('properties_allowed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('mpesa_receipt', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.drop_table('subscription_intents')
    op.drop_table('job_locks')
    # ### end Alembic commands ###
