"""initial schema

Revision ID: 5598e5f7ee68
Revises: 
Create Date: 2026-01-15 14:46:30.424964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5598e5f7ee68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('last_run', sa.Date(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('max_properties', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('login_phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('paybill_number', sa.String(length=30), nullable=True),
    sa.Column('till_number', sa.String(length=30), nullable=True),
    sa.Column('mpesa_consumer_key', sa.String(length=200), nullable=True),
    sa.Column('mpesa_consumer_secret', sa.String(length=200), nullable=True),
    sa.Column('mpesa_passkey', sa.String(length=200), nullable=True),
    sa.Column('mpesa_shortcode', sa.String(length=20), nullable=True),
    sa.Column('mpesa_env', sa.String(length=20), nullable=True),
    sa.Column('mpesa_callback_url', sa.String(length=500), nullable=True),
    sa.Column('reset_code', sa.String(length=10), nullable=True),
    sa.Column('reset_code_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_login_phone'), ['login_phone'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('meta', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landlord_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('paybill_number', sa.String(length=32), nullable=True),
    sa.Column('till_number', sa.String(length=32), nullable=True),
    sa.Column('send_money_number', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('mpesa_consumer_key', sa.String(length=255), nullable=True),
    sa.Column('mpesa_consumer_secret', sa.String(length=255), nullable=True),
    sa.Column('mpesa_shortcode', sa.String(length=32), nullable=True),
    sa.Column('mpesa_passkey', sa.String(length=255), nullable=True),
    sa.Column('mpesa_mode', sa.String(length=20), nullable=False),
    sa.Column('callback_url', sa.String(length=512), nullable=True),
    sa.Column('kcb_api_key', sa.String(length=255), nullable=True),
    sa.Column('kcb_paybill', sa.String(length=32), nullable=True),
    sa.Column('kcb_env', sa.String(length=20), nullable=False),
    sa.Column('kcb_callback_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landlord_settings_user_id'), ['user_id'], unique=False)

    op.create_table('mpesa_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shortcode', sa.String(length=50), nullable=True),
    sa.Column('shortcode_type', sa.String(length=20), nullable=True),
    sa.Column('callback_url', sa.String(length=500), nullable=True),
    sa.Column('mpesa_env', sa.String(length=20), nullable=True),
    sa.Column('encrypted_consumer_key', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_consumer_secret', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_passkey', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('properties_allowed', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_invoice_id')
    )
    op.create_table('subscription_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('payment_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('payer_account', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('clearing_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_invoice_id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('national_id', sa.String(length=80), nullable=True),
    sa.Column('house_no', sa.String(length=80), nullable=False),
    sa.Column('monthly_rent', sa.Float(), nullable=False),
    sa.Column('move_in_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_rent_update', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_property_id'), ['property_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_checkout_request_id'), ['checkout_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_checkout_request_id'))

    op.drop_table('payment')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_property_id'))

    op.drop_table('tenant')
    op.drop_table('subscription_intents')
    op.drop_table('subscription')
    op.drop_table('property')
    op.drop_table('mpesa_credential')
    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landlord_settings_user_id'))

    op.drop_table('landlord_settings')
    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login_phone'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('plan')
    op.drop_table('job_locks')
    # ### end Alembic commands ###
