"""all

Revision ID: 77fa625cf658
Revises: b9879711940b
Create Date: 2026-01-18 17:28:30.396265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fa625cf658'
down_revision = 'b9879711940b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.alter_column('master_paybill',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('master_account_format',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('bank_account_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('paybill_number')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('mpesa_passkey')
        batch_op.drop_column('till_number')
        batch_op.drop_column('mpesa_consumer_key')
        batch_op.drop_column('mpesa_consumer_secret')
        batch_op.drop_column('mpesa_shortcode')
        batch_op.drop_column('mpesa_callback_url')
        batch_op.drop_column('mpesa_env')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_env', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_callback_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_shortcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_consumer_secret', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_consumer_key', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('till_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_passkey', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paybill_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.alter_column('bank_account_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('master_account_format',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('master_paybill',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
