"""Create unit table

Revision ID: 8a5a5652dde6
Revises: a372c02605a8
Create Date: 2026-01-18 11:21:00.996118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a5a5652dde6'
down_revision = 'a372c02605a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('intasend_invoice_id', sa.String(length=50), nullable=True),
    sa.Column('intasend_ref', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('house_no', sa.String(length=20), nullable=False),
    sa.Column('payment_ref', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_ref')
    )
    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_paybill', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('master_account_format', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_branch', sa.String(length=100), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_landlord_settings_intasend_customer_ref'))
        batch_op.drop_index(batch_op.f('ix_landlord_settings_user_id'))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('mpesa_consumer_secret')
        batch_op.drop_column('mpesa_shortcode')
        batch_op.drop_column('kcb_api_key')
        batch_op.drop_column('mpesa_passkey')
        batch_op.drop_column('settlement_phone')
        batch_op.drop_column('intasend_wallet_id')
        batch_op.drop_column('mpesa_consumer_key')
        batch_op.drop_column('settlement_verified')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('payment_provider')
        batch_op.drop_column('settlement_account')
        batch_op.drop_column('mpesa_mode')
        batch_op.drop_column('intasend_customer_ref')
        batch_op.drop_column('settlement_bank_name')
        batch_op.drop_column('kcb_paybill')
        batch_op.drop_column('kcb_env')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('property_owner_id_fkey'), type_='foreignkey')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('property_owner_id_fkey'), 'user', ['owner_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('reference',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kcb_env', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kcb_paybill', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('settlement_bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('intasend_customer_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('settlement_account', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_provider', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('settlement_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_consumer_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('intasend_wallet_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('settlement_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_passkey', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kcb_api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_shortcode', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpesa_consumer_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_landlord_settings_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_landlord_settings_intasend_customer_ref'), ['intasend_customer_ref'], unique=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('bank_branch')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_account_name')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('master_account_format')
        batch_op.drop_column('master_paybill')

    op.drop_table('unit')
    op.drop_table('rent_ledger')
    # ### end Alembic commands ###
