"""add invoice table

Revision ID: a3fdf8444886
Revises: 81c640e6419d
Create Date: 2026-01-17 12:40:38.326068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fdf8444886'
down_revision = '81c640e6419d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=50), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_reference_code'), ['reference_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoice_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_provider', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('intasend_customer_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('intasend_wallet_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('settlement_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('settlement_bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('settlement_account', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('settlement_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('mpesa_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('kcb_env',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_landlord_settings_intasend_customer_ref'), ['intasend_customer_ref'], unique=True)
        batch_op.drop_column('paybill_number')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('callback_url')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('kcb_callback_url')
        batch_op.drop_column('till_number')
        batch_op.drop_column('send_money_number')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('raw_payload', sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_payment_checkout_request_id'))
        batch_op.create_index(batch_op.f('ix_payment_reference'), ['reference'], unique=False)
        batch_op.drop_column('note')
        batch_op.drop_column('checkout_request_id')

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_properties',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('property_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('is_trial',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_grace',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint(batch_op.f('subscription_plan_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('subscription_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscription_intents', ['intent_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'plan', ['plan_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscription_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('subscription_plan_id_fkey'), 'plan', ['plan_id'], ['id'])
        batch_op.alter_column('is_grace',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_trial',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('property_owner_id_fkey'), 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('max_properties',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_payment_reference'))
        batch_op.create_index(batch_op.f('ix_payment_checkout_request_id'), ['checkout_request_id'], unique=False)
        batch_op.drop_column('raw_payload')
        batch_op.drop_column('status')
        batch_op.drop_column('currency')
        batch_op.drop_column('reference')
        batch_op.drop_column('provider')

    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_money_number', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('till_number', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kcb_callback_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('callback_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paybill_number', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_landlord_settings_intasend_customer_ref'))
        batch_op.alter_column('kcb_env',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('mpesa_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('settlement_verified')
        batch_op.drop_column('settlement_account')
        batch_op.drop_column('settlement_bank_name')
        batch_op.drop_column('settlement_phone')
        batch_op.drop_column('intasend_wallet_id')
        batch_op.drop_column('intasend_customer_ref')
        batch_op.drop_column('payment_provider')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_reference_code'))

    op.drop_table('invoice')
    # ### end Alembic commands ###
